server:
  port: 9093
  servlet:
    context-path: /ac
management:
  port: 9094

spring:
  application:
    name: ops-api
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 11
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 3000
      pool-name: DatebookHikariCP
#  dubbo:
##    server: true
#     registry: zookeeper://127.0.0.1:2181
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: zwt
    password: zwt
    publisher-confirms: true
    virtual-host: bt
    connection-timeout: 3s
  redis:
    database: 3
    host: 127.0.0.1
    port: 6379

dubbo:
  scan:
    basePackages: com.example.service
  application:
    id: boot
    name: boot
    qos-port: 12306
    qos-enable: false
  protocol:
    id: dubbo
    name: dubbo
    port: 12340
#  registry:
#    id: local
#    address: zookeeper://127.0.0.1:2181

  registries:
    registry1:
      address: zookeeper://127.0.0.1:2181

  consumer:
    check: false
    timeout: 5000
    retries: 0
  provider:
    timeout: 5000

mybatis:
  type-aliases-package: com.example.entity
  mapper-locations: classpath:com/example/mapper/*.xml


mapper:
  mappers: com.example.common.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com.jumstc.ops.console.mapper: debug
